version: "2"
services:
  python:
    image: "tools/python:prod"
    build:
      context: ./python
      args:
        - ENV=production
    container_name: "tools-python"
    volumes:
      - "../:/tools/"
      - "/srv/ftp/:/srv/ftp/"
    environment:
      - ENV=production
    restart: always

  syslog:
    image: "tools/syslog-ng:prod"
    build: "syslog-ng"
    container_name: "tools-syslog"
    links:
      - "redis"
    ports:
      - "601:601"
    volumes:
      - "./syslog-ng/config/conf.d.production/:/etc/syslog-ng/conf.d/"

  redis:
    image: "redis:alpine"
    container_name: "tools-redis"
    ports:
      - "6376:6379"

  logstash:
    image: "tools/logstash:prod"
    build: "logstash"
    container_name: "tools-logstash"
    links:
      - "redis"
    volumes:
      - "./logstash/config/pipeline.production:/usr/share/logstash/pipeline"
