IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES 
           WHERE TABLE_NAME = N'@TABLE_NAME')
BEGIN
  CREATE TABLE [@TABLE_NAME](
@COLUMNS
  )

  CREATE CLUSTERED COLUMNSTORE INDEX cci_@TABLE_NAME ON @TABLE_NAME;

  SELECT * INTO __@TABLE_NAME FROM @TABLE_NAME

END
GO
