-- Generate xls of schema
SELECT 
  TABLE_NAME
,COLUMN_NAME
,DATA_TYPE
,CHARACTER_MAXIMUM_LENGTH
,NUMERIC_PRECISION
,NUMERIC_SCALE
,DATETIME_PRECISION
FROM 
  INFORMATION_SCHEMA.COLUMNS
ORDER BY 
  TABLE_NAME


  -- Generate DROP TABLE 
SELECT 
  'DROP TABLE ' + TABLE_NAME
FROM 
  INFORMATION_SCHEMA.TABLES
ORDER BY 
  TABLE_NAME


  -- Generate SELECT TABLE 
SELECT 
  'SELECT * FROM ' + TABLE_NAME
FROM 
  INFORMATION_SCHEMA.TABLES
ORDER BY 
  TABLE_NAME

-- SELECT 
SELECT COUNT(*) FROM ga_acquisition
SELECT COUNT(*) FROM ga_conversions
SELECT COUNT(*) FROM ho_transactions
SELECT COUNT(*) FROM ho_performance

SELECT * FROM ga_acquisition

-- CREATE TEMP TABLE
SELECT * INTO __ho_performance FROM ho_performance
