# -*- coding: utf-8 -*-

CURRENCY_TO_COUNTRY = {'IDR': 'ID', 'MYR': 'MY', 'PHP': 'PH', 'SGD': 'SG', 'THB': 'TH', 'VND': 'VN', 'HKD': 'HK'}

COUNTRY_TO_CURRENCY = {'ID': 'IDR', 'MY': 'MYR', 'PH': 'PHP', 'SG': 'SGD', 'TH': 'THB', 'VN': 'VND', 'HK': 'HKD'}

PARTNERS = {
    'MP1000': 'SAYS',
    'MP0001': 'SAYS',  # backwards compatibility
    'MP1001': 'JUICE',
    'MP1002': 'HANGER',
    'MP1003': 'RAPPLER',
    'MP1004': 'OHBULAN'
}

OS = {
    'Desktop': 'desktop',
    'Mac OS X': 'desktop',
    'OS X': 'desktop',
    'iOS': 'mobile',
    'ios': 'mobile',
    'Android': 'mobile',
    'Android Mobile': 'mobile',
    'Windows Phone OS': 'mobile',
    'RIM OS': 'mobile',
    'Symbian OS': 'mobile',
    'MeeGo': 'mobile',
    'Windows RT': 'mobile',
    'Windows Mobile OS': 'mobile',
    'MTK/Nucleus OS': 'mobile',
    'RIM Tablet OS': 'mobile',
    'Tizen': 'mobile',
    'PlayStation OS': 'mobile',
    'Firefox OS': 'mobile',
    'Windows': 'desktop',
    'Windows XP': 'desktop',
    'Windows Vista': 'desktop',
    'Windows 7': 'desktop',
    'Windows 8': 'desktop',
    'Windows 8.1': 'desktop',
    'Windows 10': 'desktop',
    'Linux': 'desktop',
    'Ubuntu': 'desktop',
    'Chrome OS': 'desktop',
    'Android 4.x': 'mobile',
    'Android 5.x': 'mobile',
    'Android 4.x Tablet': 'mobile',
    'Android 5.x Tablet': 'mobile',
    'iOS 6 (iPhone)': 'mobile',
    'Windows Phone': 'mobile',
    'RIM': 'mobile',
    'BlackBerryOS': 'mobile',
    'BlackBerry OS': 'mobile',
    'android': 'mobile',
    'Fire OS': 'mobile',
}

BROWSERS = {
    'Partially Web-Capable Devices': 'mobile',
    'WML-Only Devices': 'mobile',
    'NetFront Browser (newer devices)': 'mobile',
    'Android': 'mobile',
    'android': 'mobile',
    'Tizen': 'mobile',
    'iPad': 'mobile',
    'iPhone / iPod': 'mobile',
    'BlackBerry (newer devices)': 'mobile',
    'Firefox': 'desktop',
    'Internet Explorer': 'desktop',
    'Chrome': 'desktop',
    'Safari': 'desktop',
    'Opera': 'desktop',
    'Other': 'desktop'
}

MERCHANTS = {
    "VN Megamart": "megamart|megamart.vn",
    "TH Ucall Shop": "ucall|ucall.in.th",
    "TH Ensogo": "ensogo|ensogo.co.th",
    "MY Baby Needs": "babyneeds-cheras.com|babyneeds-cheras.com",
    "HK Merimobiles": "merimobiles|merimobiles.com",
    "RedMart Limited": "redmart|redmart.com",
    "ZALORA - VN": "zalora|Zalora.vn",
    "Zalora (ID)": "zalora|Zalora.id",
    "Printcious": "printcious|printcious.com",
    "SSar News Subscription": "SSar News|SS178",
    "SG Hermo.sg (OLD)": "hermo|Hermo.sg",
    "TH Super rich": "super-rich|super-rich.com",
    "Poplook (MY)": "poplook|poplook.com",
    "SG Axtro Sports": "axtroSports|axtrosports.com",
    "MY Muscle Club": "muscle-club-malaysia|muscleclubmalaysia.com",
    "MY farhabyjz.com": "farhabyjz|farhabyjz.com",
    "(SC) MY, SG, PH & HK TinySand": "tinysand|tinysand.com",
    "PH Unlideals": "unlideals|unlideals.com",
    "MY Althea": "althea|my.althea.kr",
    "PH Latestgadget.com": "latest-gadget|latestgadget.com.ph",
    "Apple (SG)": "apple|apple.com",
    "MY Oh Baby Store": "oh-baby-store|ohbaby.com.my",
    "VN DONGHOVUA.COM": "donghovua.com|donghovua.com",
    "EasyUni": "easyUni|easyuni.com",
    "Nescafe": "nescafe|nestle.co.th",
    "ID FurnishLab": "furnishlab|furnishlab.com",
    "Yes24 - Mua sắm online phong cách Hàn Quốc": "yes24|yes24.vn",
    "VN manhnguyen.com.vn": "manhnguyen|manhnguyen.com.vn",
    "VN Hoayeuthuong.com": "hoayeuthuong|hoayeuthuong.com",
    "Galleon PH Coupons": "galleon|galleon.ph",
    "VN Laptopnew.vn": "laptopnew|laptopnew.vn",
    "Expedia Indonesia": "expedia|expedia.co.id",
    "MY Camera2u": "camera2u|camera2u.com",
    "Apple Online Store": "apple|apple.com",
    "PH Mall Icons": "mallicons|mallicons.com",
    "SG Superberry": "superberry|superberry.me",
    "ID Frozenshop": "frozen|frozenshop.com",
    "VN Laptop123.vn": "laptop123|laptop123.vn",
    "(SC) SG, HK, PH, ID 1030AM": "1030am|1030am.my",
    "ID D-Island": "d-island|d-island.com.my",
    "PH Sephora": "sephora|sephora.ph",
    "Konvy  laneige     10%": "konvy|konvy.com",
    "MY VK Technology Online": "vktechonline|vktechonline.com",
    "VN Thienbaostore.com": "thien-bao-store|thienbaostore.com",
    "SG EXPANSYS": "expansys|expansys.com.sg",
    "ZALORA SG": "zalora|zalora.sg",
    "SG Lara 'J": "lara-j|lara-j.com",
    "VN alola.vn": "alola|alola.vn",
    "PH Remal Sales": "remalsales|remalsales.com",
    "HK Best Buy World": "hk.bestbuy-world|my.bestbuy-world.com",
    "PH YiLinker": "yiLinker|yilinker.com",
    "MY qoo10": "apartment8clothing|apartment8clothing.com",
    "(SC) MY,SG SkincareHq": "origins|origins.com.sg",
    "F.O.S": "fos|fos.com.my",
    "MY Colours Cosmetics": "colours-cosmetics|colourscosmeticsmalaysia.com",
    "PH Ensogo": "ensogo|ensogo.com.ph",
    "DELETED - Rakuten": "rakuten|global.rakuten.com",
    "SG CompAsia": "comp-asia|sg.comp-asia.com",
    "Major Drop (MY)": "major-drop|majordrop.com",
    "FoodPanda Singapore": "foodpanda|foodpanda.sg",
    "MY HiTec Mobile": "hitec-mobile/my|hitecmobiles.com",
    "Althea": "althea|my.althea.kr",
    "VN Lagihitech.vn": "lagihitech|lagihitech.vn",
    "VN Maxbuy.vn": "maxbuy|maxbuy.vn",
    "Expedia Hongkong": "expedia|expedia.com.hk",
    "Kily Philippines coupons": "kily-philippines|kily.ph",
    "ID Zataru.com": "zataru|zataru.com",
    "Qoo10": "qoo10|qoo10.my",
    "SG Digitalmall": "digitalmall|digitalmall.com.sg",
    "ID Unicorner": "unicorner|unicorner.co.id",
    "TH 1577 Shop": "1577shop|1577shop.com",
    "HK Triple Time Watch": "triple-time-watch|tripletimewatch.com",
    "VN thegioibluetooth.vn": "thegioibluetooth|thegioibluetooth.vn",
    "PH Takatack": "takatack|takatack.com",
    "VN vuabanle.vn": "vuabanle|vuabanle.vn",
    "VN Dien May Binh Minh": "dien-may-cho-lon|dienmaybinhminh.com",
    "Gameon": "gameon|gameon.com.my",
    "VN Alovendor.com": "alovendor|alovendor.com",
    "Supermodels Secrets": "supermodels-secrets|supermodel2u.com",
    "VN 868.vn": "868vn|868.vn",
    "MY Justbuy": "justbuy|justbuy.com.my",
    "ID Oktagon": "oktagon|oktagon.co.id",
    "Tiki.vn - Trải nghiệm mua sắm trực tuyến tuyệt vời": "tikivn|tiki.vn",
    "Berrybenka": "berrybenka|berrybenka.com",
    "Berrybenka (ID)": "berrybenka|berrybenka.com",
    "GlassesGroup AsiaPacific Sdn Bhd MY": "glassesonline|glassesonline.com.my",
    "Deal": "deal|ST469",
    "SG iMOB Shop": "imobshop|imobshop.sg",
    "Cincaibuy": "cincaibuy|cincaibuy.com",
    "DELETED - Cincaibuy": "cincaibuy|cincaibuy.com",
    "PH Galleon (Caps reached)": "galleon|galleon.ph",
    "SG Ezbuy": "ezbuy|ezbuy.sg",
    "PT Tees Pratama Indonesia (Tees.co.id)": "teescoid|tees.co.id",
    "MY Clickasia": "clickasia|clickasia.my",
    "(ALL) HK YesStyle": "yesstyle|yesstyle.com",
    "PH BS Mobile": "bs-mobile|manila.bsmobile.com.ph",
    "MY Ewatchzone": "ewatchzone|shop.ewatchzone.com",
    "ID Agen Elektronik": "agenelektronik|agenelektronik.com",
    "Adayroi - Giao hàng siêu tốc, giá sốc mỗi ngày": "adayroi|adayroi.com",
    "ZUJI Australia": "zuji|.zuji.com.au",
    "Rakuten Thailand": "rakuten|global.rakuten.com",
    "PH PC Express": "pc express|pcx.com.ph",
    "SG GameShop": "gameshopasia|gameshopasia.com",
    "tohome.com ช้อปปิ้งออนไลน์สินค้าไอทีครบวงจร แบรนด์ชั้นนำ ราคาสุดประหยัด": "tohome|tohome.com",
    "MY Life Good Online": "mystudylife|mystudylife.com",
    "MY F Block": "fblock|fblock.com.my",
    "MY EN mastar": "mastar|mastar.com.my",
    "VN kangaroohanoi.vn": "kangaroohanoi|kangaroohanoi.vn",
    "VN Penda (Fashion)": "penda|penda.vn",
    "ID Bobobobo": "bobobobo|bobobobo.com",
    "BOBOBOBO": "bobobobo|bobobobo.com",
    "Sephora": "sephora|sephora.my",
    "TH Sakura Mobile": "sakuramobile|sakuramobile.tarad.com",
    "VN Phucanh.vn": "phucanh|phucanh.vn",
    "VN OkBuy.vn": "okbuyvn-mua-sam|okbuy.vn",
    "F": "fos|fos.com.my",
    "ServisHero (MY)": "servishero|servishero.com",
    "BagBeg": "bagbeg|bagbeg.com",
    "ID Mangga Dua Komputer": "manggaduakomputer|manggaduakomputer.com",
    "MY Halomama.com Baby Store": "halomama|halomama.com",
    "SG Gobuylah": "gobuylah|gobuylah.sg",
    "ID Wearinasia": "wearinasia|wearinasia.com",
    "HK Sephora": "sephora|sephora.hk",
    "Share revenue with eatigo, no.1 reservation app of Thailand!!": "eatigo|eatigo.com",
    "ID Batam Online Shop": "batam-online-shop|batamonlineshop.com",
    "(ALL) MY SG TH ID VN PH HK WHOLESALE7.NET": "wholesale7|wholesale7.net",
    "MYMALL.VN – MỖI NGÀY MUA SẮM MỖI NGÀY VUI": "mymall|mymall.vn",
    "F.O.S (MY)": "fos|fos.com.my",
    "TH topvalue.com": "topvalue|topvalue.com",
    "Singli HK Coupons": "singli|singli.com",
    "Stylebop": "stylebop|stylebop.com",
    "MY JML.com.my": "jml|jml.com.my",
    "Air Asia Go (SG)": "airasia|airasia.com",
    "Booking.com Thailand": "bookingcom)|booking.com",
    "(ALL) MY SG TH ID VN PH HK YesStyle": "yesstyle|yesstyle.com",
    "HK mabelle.com": "mabelle|mabelle.com",
    "PH Syala Collections": "syala|syalacollections.com",
    "MY Ezi Buy": "ezibuy|ezibuy.my",
    "TH G-Play-System": "g-play-system|g-play-system.com",
    "(SC) SG,HK,PH,MY Purpur": "purpur|purpur.com.sg",
    "VN bep365.vn": "bep365|bep365.vn",
    "HK FlowerAdvisor": "floweradvisor|floweradvisor.com.hk",
    "Rakuten Malaysia": "rakuten|global.rakuten.com",
    "PH Expansys": "xxpansys|expansys.com",
    "ID Digi": "digi|digi.co.id",
    "TH Thaielectricworld.info": "thaielectricworld|thaielectricworld.info",
    "TH THE OUTLET24": "theoutlet24.com|theoutlet24.com",
    "(ALL) MY SG TH ID VN PH HK Jollychic.com": "jollychic|jollychic.com",
    "VN Viethungepc.com": "viethungepc|Viethungepc.com",
    "iprice test": "iprice test|iprice test",
    "ID BlackSpex": "blackspex|blackspex.co.id",
    "MY Jelitasara.com": "jelitasara|jelitasara.com",
    "HK eFul": "eful|eful.com",
    "SG Sonic Sound Audio": "sonicsoundaudio|sonicsoundaudio.com",
    "TH Fashionkibkea": "fashionkibkea|fashionkibkea.tarad.com",
    "Glasses Online": "glassesonline|glassesonline.com.my",
    "DigitalRev Cameras": "digitalrev|digitalrev.com",
    "PH GadgetPinas": "gadgetpinas|gadgetpinas.ph",
    "Mille Online Shop": "mille-beaute|millebeaute.com",
    "Say ion FashAffiliate Program": "say fashion|SS471",
    "ID Tororo": "tororo|tororo.com",
    "HK 4Deco": "4deco|4deco.com.hk",
    "VN Bepthaison.vn": "Bepthaison|bepthaison.vn",
    "Test Store": "test|nan",
    "ID Damn! I Love Indonesia": "damn-i-love-indonesia|damnIioveindonesia.com|",
    "sieuthivip.vn VN": "sieuthivip|sieuthivip.vn",
    "MY BagBeg": "bagbeg|bagbeg.com",
    "SmartBuyGlasses / VisionDirect": "smartbuyglasses|smartbuyglasses.com",
    "(SC) HK, MY, SG, PH, ID Yoox.com": "yoox|yoox.com",
    "VN Zanado": "zanado|zanado.com",
    "TH OK2Home.com": "ok2home|OK2Home.com",
    "Winetalk MY Coupons": "winetalk|winetalk.com.my",
    "VN Loagiare": "loa-gia-re|loagiare.com",
    "VN Thenhominhhang.com": "thenhominhhang|thenhominhhang.com",
    "MY Krissu Fashion": "krissu-fashion|krissufashion.biz",
    "PT FASHION ESERVICES INDONESIA": "nan|nan",
    "PH WidgetCity": "widgetcity|widgetcity.com.ph",
    "VN Casiovietnam.net": "casio-vietnam|casiovietnam.net",
    "GCJ O-Shopping": "gcj-oshopping-tv|oshoppingtv.com",
    "VN Hong Phuc Sport": "dothethao|dothethao.net.vn",
    "Groupon Indonesia": "groupon|groupon.co.id",
    "ช้อปวันนี้ที่ Cdiscount": "cdiscount|cdiscount.com",
    "VN dealgiare.vn": "dealgiare|dealgiare.vn",
    "SG StyleTribute": "styletribute|styletribute.com",
    "MY Glampot": "glampot|e-glampot.com",
    "DELETED - cincaibuy": "Cincaibuy|cincaibuy.com",
    "Trivago (MY)": "trivago|trivago.com.my",
    "MY Pudore": "pudore|pudore.com.my",
    "Groupon HK": "groupon|groupon.hk",
    "PH CameraHaus": "camerahaus|camerahaus.com",
    "AIS Shopping Online": "ais-shopping-online|store.ais.co.th",
    "VN phukiengalaxy.vn": "Phukiengalaxy.vn|phukiengalaxy.vn",
    "1030am.com": "1030am|1030am.com",
    "SG HiTec Mobile": "hitec-mobile|hitecmobile.com.sg",
    "MY TUESDAY C.": "tuesday-couture|tuesdaycouture.com",
    "Cameralah": "cameralah|cameralah.com",
    "Jade Eservices Malaysia Sdn Bhd (Zalora Malaysia)": "zalora|zalora.com.my",
    "Carama by Castrol": "carama|carama.com",
    "MY Kime.com.my": "kime|kime.com.my",
    "3% commission  order  moxy": "moxy|orami.co.th",
    "SG Treoo": "treoo|store.treoo.com",
    "HIS TOURS affiliate campaign": "his-go|hisgo.com",
    "(SC) MY, SG, PH, HK Better Brands": "better-brand|betterbrands.com.au",
    "PH PhilPerfume.com": "philperfume|philperfume.com",
    "AYO": "ayo-ayo|ayo.com.au",
    "Poplook": "poplook|poplook.com",
    "VN Putago": "putago|putago.vn",
    "ID Blanja": "blanja|blanja.com",
    "VN binhminhdigital.com": "dien-may-binh-minh|binhminhdigital.com",
    "Zen Zen Dream (MY)": "zenzen-dream|zenzendream.com",
    "ID IndoGeotech": "indogeotech|indogeotech.com",
    "RedMart Singapore": "redmart|redmart.com",
    "PH CMK Cellphones": "cmk|cmkcellphones.com",
    "VN Shopxedap.vn": "shopxedap|Shopxedap.vn",
    "SG Lion City Company": "lioncityco|lioncityco.com",
    "HK Lingsik": "lingsik|lingsik.com",
    "Kiehl": "kiehl-th|kiehls.co.th",
    "ID Bhinneka": "bhinneka|bhinneka.com",
    "TH hitechshoponline": "hitechshoponline|hitechshoponline.com",
    "ETCLO ID Coupons": "etclo|etclo.com",
    "MY Expansys": "expansys|expansys.my",
    "TH Studio Phone": "studiophone|studiophone.co.th",
    "VN VietnamsFlorist": "vietnamsflorist|vietnamsflorist.com",
    "Apple Online Store (MY)": "apple|apple.com",
    "Konvy.com  อัพเดตโปรโมชั่นสุดเอ็กซ์คลูซีฟ! ทุกสัปดาห์  รวมเครื่องสำอางโปรโมชั่นแรง! จากทั่วมุมโลก": "konvy|konvy.com",
    "Hermo": "hermo|hermo.my",
    "MY SB Wines and Spirit": "sbwinesnspirit|sbwinesnspirit.com",
    "PH Go Buy": "gobuy|obuy.com.ph",
    "SG Skywatches": "skywatches|skywatches.com.sg",
    "SG Sephora": "sephora|sephora.sg",
    "TH Ookbee Mall": "ookbeemall|ookbeemall.com",
    "TeezBee": "teezbee|teezbee.com",
    "MY Winetalk": "winetalk|winetalk.com.my",
    "DELETED - Say Fashion Affiliate Program": "Say Fashion|SS471",
    "TH pause21.com": "pause21|pause21.com",
    "VN dienmaythudo.com": "dienmaythudo|dienmaythudo.com",
    "MY Gameshop": "gameshop|gameshop.my",
    "SG Alltronic Computer": "alltroniccomputer|alltroniccomputer.com.sg",
    "Carama.com Malaysia": "romwe|carama.com",
    "MY 1030AM": "1030am|1030am.com",
    "VN Anchau.vn": "anchau|anchau.vn",
    "(ALL) HK WHOLESALE7.NET": "wholesale7|wholesale7.net",
    "PT Shopdeca Global": "shopdeca|shopdeca.com",
    "MY Youbeli.com": "youbeli|youbeli.com",
    "PH YouPoundit": "youpoundit|youpoundit.com",
    "PH Eazy Fashion": "eazyfashion|eazyfashion.com",
    "TH FlowerAdvisor": "floweradvisor|floweradvisor.co.th",
    "PH FurnitureManila": "furnituremanila|furnitureManila.com.ph",
    "MY Oribags": "oribags|oribags.com",
    "Konvy.com จัดโปรโมชั่นพิเศษเดือนมิถุนายน อัพเดตสินค้า Top 20 ประจำเดือน พร้อมราคาสุดพิเศษ": "konvy|konvy.com",
    "MY IdeaShop.my": "ideashop|ideashop.my",
    "MY GameOn": "gameon|gameon.com.my",
    "AAE Travel Pte Ltd": "aaetravel|aaetravel.com",
    "Vivere Rosse (MY)": "vivere-rosse|vivererosse.com",
    "ID Orami": "orami|orami.co.id",
    "I Babyland": "i-babyland|i-babyland.com",
    "Booking.com Singapore": "bookingcom|booking.com",
    "b.liv (MY)": "bliv|bliv.com",
    "MY MRuncit": "mruncit|mruncit.com",
    "N Store": "nstore|Nstore.net",
    "HK Imiba": "i-miba|i-miba.com",
    "MY TUESDAY C. (Old offer)": "tuesday-couture|tuesdaycouture.com",
    "VN Tablet Plaza": "tabletplaza|tabletplaza.vn",
    "PH Style Compass": "style-compass|stylecompass.ph",
    "Pegipegi": "pegipegi|Pegipegi.com",
    "PegiPegi (ID)": "pegipegi|Pegipegi.com",
    "1  asia direct broker": "asia-direct|asiadirect.co.th",
    "Expedia Malaysia": "expedia|expedia.com.my",
    "VN Hnammobile.com": "hnammobile|hnammobile.com",
    "Vivere Rosse": "vivere-rosse|vivererosse.com",
    "ID Sephora": "sephora|sephora.id",
    "PH Bayan Mall": "bayanmall|bayanmall.com",
    "Tmart.com": "tmart|tmart.com",
    "SG Bata.com.sg": "bata|bata.com.sg",
    "VN FlowerAdvisor": "floweradvisor|floweradvisor.com",
    "VN Didong.pro": "didong.pro|didong.pro",
    "Qoo10.co.id": "Qoo10|qoo10.co.id",
    "MY Limkokwing Fashion Club": "fashionclub|fashionclub.my",
    "Bello2": "bello2|bello2.com",
    "TH Watch2home": "watch2home|watch2home.com",
    "Kyra Mode": "kyra|kyramode.com",
    "MY kcareshop.com": "kcareshop|kcareshop.com",
    "ID AlatMobil.com": "alatmobil|alatmobil.com",
    "WearYouWant": "wearyouwant|wearyouwant.com",
    "5% commission  order  moxy": "moxy|moxy,orami.co.th",
    "MY Faliyana Mom Store": "faliyana-mom-store|a.faliyanamomstore.com",
    "MY JemmyFashion": "jemmyfashion|jemmyfashion.com",
    "Test campaign for partners -CPS-": "test|nan",
    "MY Maxaudio.com.my": "maxaudio|maxaudio.com.my",
    "THANN ONLINE STORE": "thann|thann.co.th",
    "LushProtein (SG)": "lushprotein|lushprotein.com",
    "เซ็ทของขวัญสุดคุ้มจากคีลส์ (มีจำนวนจำกัด) Kiehl's": "kiehls|kiehls.co.th",
    "iTrueMart Shopping Online": "ituremart|itruemart.ph",
    "SheIn": "shein|shein.com",
    "MY i-rova": "i-rova|i-rova.com",
    "ID More by Morello": "morebymorello|morebymorello.com",
    "MY Hermo.my (OLD)": "hermo|hermo.my",
    "VN osm.com.vn": "osm|osm.com.vn",
    "MY Logon": "logon|logon.my",
    "ID Tees.co.id": "teescoid|tees.co.id",
    "ID Grosir Fashion Online": "grosirfashiononline|grosirfashiononline.com",
    "Agoda Company Pte Ltd": "agoda|agoda.com",
    "VN Sendo.vn": "sendo|sendo.vn",
    "MY BigBigPlace": "big-big-place|bigbigplace.com",
    "HonestBee": "honestbee|honestbee.my",
    "Trivago (MY-Mobile)": "trivago|trivago.com.my",
    "ID Buah Hatiku": "buahhatiku|buahhatiku.com",
    "PH laptopkid": "laptopkid|laptopkid.com",
    "LushProtein": "lushprotein|lushprotein.com",
    "Eatigo": "eatigo|eatigo.com",
    "Wego Travel Search": "wego|wego.com.my",
    "VẬT GIÁ - Sàn giao dịch Thương mại điện tử hàng đầu tại Việt Nam": "vatgia|vatgia.com",
    "Sanoga": "sanoga|sanoga.com",
    "ID Bukalapak": "bukalapak|bukalapak.com",
    "Smartbuyglasses": "smartbuyglasses|smartbuyglasses.com",
    "CHARLESKEITH.COM PTE LTD": "charleskeith|charleskeith.com",
    "MY Sold.my": "sold|sold.my",
    "voucher": "voucher|nan",
    "ID Otten Coffee": "otten-coffee.co.id|ottencoffee.co.id",
    "ID Perfectbeautyshop": "perfect-beauty|perfectbeauty.me",
    "Trivago (Desktop)": "trivago|trivago.com.my",
    "Kei Mag (MY)": "keimag|keimag.com.my",
    "VN Vivamall": "vivamall|vivamall.vn",
    "MY SummerGlitz.com.my": "summerglitz|summerglitz.com.my",
    "SG Harvey Norman": "harveynorman|harveynorman.com.sg",
    "ZALORA - HK": "zalora|zalora.com.hk",
    "ID ETCLO": "etclo|etclo.com",
    "PH Solidmark": "solidmark|solidmark.com.ph",
    "HK Mblife.com": "mblife|mblife.com",
    "VN SIEUTHIVIP.VN": "sieuthivip|sieuthivip.vn",
    "ID Damn! I Love Indonesia Test": "damn-i-love-indonesia|damniloveindonesia.com",
    "(SC) MY,SG,ID,PH,HK Halomama.com Baby Store": "halomama|halomama.com",
    "PH Ametech.us": "ametech|ametech.us",
    "VN nhanhavui.com.vn": "nhanhavui|nhanhavui.com.vn",
    "ช็อปวันนี้ที่ TV Direct Online Shopping": "tvdirect|tvdirect.tv",
    "Hermo MY Coupons": "hermo|hermo.my",
    "VN Dochoididong.com": "dochoididong|Dochoididong.com",
    "VN dienlanh50.com": "dienlanh50|dienlanh50.com",
    "SG Gameshome": "gameshome|gameshome.com.sg",
    "ID Nadeko": "nadeko|nadeko.co.id",
    "Say Fashion": "Say Fashion|SS473",
    "Whitesoot": "whitesoot|whitesoot.com",
    "TH Gadget Door": "gadgetdoor|gadgetdoor.com",
    "PH ebuyph.com": "ebuyph|ebuyph.com",
    "Jacob Time": "jacob-time|jacobtime.com",
    "ID Wahana Superstore": "wahana-superstore|wahanasuperstore.com",
    "ID Salmanshop": "salmanshop|salmanshop.com",
    "HK Expansys": "expansys|expansys.com.hk",
    "MatahariMall": "matahari-mall|mataharimall.com",
    "MatahariMall (ID)": "matahari-mall|mataharimall.com",
    "Bonia (MY)": "bonia|bonia.com",
    "Bonia (SG)": "bonia|bonia.com",
    "MY GEMFIVE": "fashionvalet|gemfive.com",
    "VN Vohoang.vn": "vohoang|Vohoang.vn",
    "HK COSME-DE.COM": "cosme-de|cosme-de.com",
    "Kei Mag": "keimag|keimag.com.my",
    "MY TMT": "mytnt|my.tnt.com",
    "Reebonz (MY)": "reebonz|reebonz.com.my",
    "MY WhatHeWants": "whathewants|whathewants.com.my",
    "DELETED - Seoulsia": "seoulsia|SS366",
    "VN Sieuthithanhcong.com": "sieuthithanhcong|sieuthithanhcong.com",
    "MY CompAsia": "comp-asia|comp-asia.com",
    "Trivago": "trivago|trivago.com.my",
    "VN dienmaynguyenha.com": "dienmaynguyenha|dienmaynguyenha.com",
    "MY Directd": "directd|directd.com.my",
    "MY Wedding.com.my": "weddingcommy|shop.wedding.com.my",
    "SG Expansys": "expansys|expansys.com.sg",
    "ID GoGoMall": "gogomall|gogomall.co.id",
    "(SC) SG,MY,PH,ID,HK iherb.com": "iherb|my.iherb.com",
    "DELETED - Ensogo": "ensogo|Ensogo.com.my",
    "VN anphatpc.com.vn": "anphatpc|anphatpc.com.vn",
    "TH ledtvpro": "ledtvpro|ledtvpro.com",
    "(SC) MY, PH & SG COSME-DE.COM": "cosme-de|cosme-de.com",
    "PH Tactical Asia": "tactical-asia|tacticalasia.com",
    "PH Complink.com.ph": "complink|Complink.com.ph",
    "ID Berrybenka.com": "berrybenka|berrybenka.com",
    "VN dienmaykhanghuy.vn": "dienmaykhanghuy|dienmaykhanghuy.vn",
    "SG Ensogo": "ensogo|Ensogo.com.sg",
    "VN Penda": "penda.vn|penda.vn",
    "SG ezbuy": "ezbuy|ezbuy.sg",
    "Seoulsia": "seoulsia|SS366",
    "ช้อป แชนแนล ออนไลน์ คุณภาพจากญี่ปุ่น ShopCH": "shopch|shopch.in.th",
    "Tiamo (MY)": "tiamo|tiamo.com.my",
    "ID Unomax": "unomax|Unomax.com",
    "ID Cantik": "cantik|cantik.com",
    "(SC) HK,MY,PH,ID,SG Forest Tone": "foresttone|foresttone.com",
    "MY MMAOutfit": "mmaoutfit|mmaoutfit.com",
    "MY Signature Snack": "signaturesnack|signaturesnack.com",
    "VN lanhuongmart.vn": "lanhuongmart|lanhuongmart.vn",
    "TOPICA Native: เรียนภาษาอังกฤษที่บ้าน": "topicanative|topicanative.co.th",
    "SG Bizgram": "bizgram|bizgram.com",
    "HK EasyTalk": "easy-talk|HO1005",
    "Konvy.com พบกับสินค้า Top 20 โปรโมชั่นพิเศษ เดือน สิงหาคมนี้": "konvy|konvy.com",
    "HK Bishop Luxury": "bishop-luxury|bishopluxury.com",
    "LocalBrand.co.id": "localbrand|LocalBrand.co.id",
    "MY Juzfit": "juzfit|juzfit.com",
    "VN Shoptunganh.com": "shoptunganh|Shoptunganh.com",
    "MY Banyak Deal": "banyakdeal|banyakdeal.com",
    "Colours Cosmetics MY Coupons": "colours-cosmetics|colourscosmeticsmalaysia.com",
    "BF JADE-E Services Phils Inc (Zalora Philippines)": "zalora|zalora.com.ph",
    "TH Munkong Gadget": "munkonggadget|munkonggadget.com",
    "Commission สูงถึง 10% THEOUTLET24 สินค้าแฟชั่นแบรนด์ดังจาก Central": "theoutlet24|theoutlet24.com",
    "MY FlowerAdvisor": "floweradvisor|floweradvisor.com.my",
    "MY MILKTEE": "milktee|milktee.nu",
    "SG WhatHeWants": "whathewants|whathewants.com.sg",
    "VN Babo": "babovn|babo.vn",
    "DELETED - Say Fashion": "Say Fashion|SS471",
    "VN Viviane": "viviane|viviane.vn",
    "Konvy.com พบกับสินค้า Top 20 โปรโมชั่นพิเศษ เดือน กรกฎาคมนี้": "konvy|konvy.com",
    "Luxurious Craving MY Coupons": "luxurious-craving|luxuriouscraving.com",
    "Touristly": "touristly|touristly.com",
    "PH DynaQuest PC": "dynaquest-pc|dynaquestpc.com",
    "MY Ezbuy": "ezbuy|ezbuy.my",
    "Value Basket Malaysia": "valuebasket|valuebasket.com",
    "Groupon Malaysia": "groupon|groupon.my",
    "MY MEM Watches": "mem-watches|mem-watches.com",
    "ID Bass Audio": "bass-audio|bassaudio.net",
    "Berrybenka.com": "berrybenka|berrybenka.com",
    "TOP MOT - Website Flash Sales đầu tiên tại Việt Nam": "topmot|topmot.vn",
    "VN Shopchoang.vn": "Shopchoang|shopchoang.vn",
    "Glampot": "glampot|e-glampot.com",
    "Rakuten Singapore": "rakuten|rakuten.com.sg",
    "Cdiscount - Xôn xao giá rẻ!": "cdiscount|cdiscount.vn",
    "ZALORA - TH": "zalora|zalora.co.th",
    "TH Akihabara": "akibkk|akibkk.com",
    "TH Thaimobileoutlet": "thaimobileoutlet|thaimobileoutlet.com",
    "ID Perkakasku": "perkakasku|perkakasku.com",
    "Thann online store": "thann|thann.co.th",
    "MY Greeco (Products)": "greeco-venture|gifts.greeco.com.my",
    "Easydeal": "easydeal|easydeal.com.my",
    "HK Singli": "singli|singli.com",
    "NESCAFÉ Dolce Gusto เครื่องชงกาแฟสุดชิคจาก NESCAFÉ มอบคอมมิชชั่นสูงถึง 11.55%": "nescafe|nestle.co.th",
    "TH Beauticool.com": "beauticool|beauticool.com|",
    "MY EN Dipped Row": "dipped-row|dippedrow.com",
    "HERMISO.com (MY)": "hermiso|hermiso.com",
    "East Dane": "eastdane|eastdane.com",
    "SG Streetdeal": "streetdeal|Streetdeal.sg",
    "Hermo (MY)": "hermo|hermo.my",
    "TOPICA-Asia: เรียนภาษาอังกฤษที่บ้าน:": "topica-asia|topica.asia",
    "Central": "central-online|central.co.th",
    "TH RealGadd": "realgadd|realgadd.com",
    "Shopat24 ชื่อใหม่ของ Shopat7": "shopat24|shopat24.com",
    "Apple Online Store (SG)": "apple|apple.com",
    "Sejasa (ID)": "sejasa|sejasa.com",
    "Zalora (MY)": "zalora|zalora.com.my",
    "SG BalloonManiacs": "balloonmaniacs|balloon-maniac.myshopify.com",
    "VN maytinhpt.vn": "maytinhpt|maytinhpt.vn",
    "HK MyPrincessyoyo.com": "myprincess|us.myprincessyoyo.com",
    "FoodPanda Malaysia": "foodpanda|foodpanda.my",
    "VN 338.vn": "338vn|338.vn",
    "ID Gamer Jakarta": "gamerjakarta|gamerjakarta.com",
    "SG GameShop Asia": "gameshopasia|gameshopasia.com",
    "HK Magic-Pro": "magicpro|magic-pro.com",
    "MY PINENG": "pineng|pineng.com.my",
    "TOPICA-Asia: เรียนภาษาอังกฤษที่บ้าน": "topica-asia|topica.asia",
    "VN Evashop": "evashop|evashop.com.vn",
    "MY SOUFEEL": "soufeel|soufeel.com.my",
    "Galleon PH (Caps reached)": "wearyouwant|wearyouwant.com",
    "SG Officesg": "officesg|officesg.com",
    "TH AV digital center": "avdigitalcenter|avdigitalcenter.com",
    "ID Kliknklik": "kliknklik|kliknklik.com",
    "Air Asia Go (HK)": "airasiago|airasia.com",
    "ServisHero": "servishero|servishero.com",
    "ID Modemku": "modemku|modemku.com",
    "(SC) MY,SG,PH,ID,HK Popmap": "popmap|popmap.com",
    "HK Linke": "linke|linke.hk",
    "MY Royal Selangor": "royal-selangor|royalselangor.com",
    "HK Popmap": "popmap|popmap.com",
    "SG FlowerAdvisor": "floweradvisor|floweradvisor.com.sg",
    "MY Gogguv": "gogguv|gogguv.com",
    "skilllane course online": "skillane|skilllane.com",
    "SG KS Online": "ksonline|ksonline.sg",
    "MY Sports-wear": "sports-wear|sports-wear.com.my",
    "PH Kids Company": "kids-company|kidscompany.com.ph",
    "iLightPlus หลอดไฟอัจฉริยะ": "ilightplus|ilightplus.com",
    "MY Motherhood.com.my": "motherhood|motherhood.com.my",
    "3.46% commission ทุก Order กับร้านค้าออนไลน์ชั้นนำ Orami": "moxy|orami.co.th",
    "DELETED - Fashion Valet": "fashionvalet|gemfive.com",
    "Amnig": "amnig-online|amnig.com.my",
    "VN tuanthanh.com.vn": "tuanthanh|tuanthanh.com.vn",
    "ID kicaukecil": "kicau-kecil|kicaukecil.com",
    "PH Galleon": "galleon|galleon.ph",
    "Shogun2U": "shogun2u|shogun2u.com",
    "MDreams": "mdreams|mdreams.com.sg",
    "iprice test offer": "Test|nan",
    "Photobook": "photobook|photobook.com.my",
    "TARAD.com": "tarad|tarad.com",
    "VN Vinhphatmobile.com": "vinhphatmobile|vinhphatmobile.com",
    "MY Hermo.my": "hermo|hermo.my",
    "TH Doogee Thailand": "doogeethailand|doogeethailand.com",
    "Central.co.th": "central-online|central.co.th",
    "TravelBook": "travel-book|travelbook.ph",
    "DELETED - Rakuten (MY)": "rakuten|global.rakuten.com",
    "BliBli (ID)": "blibli|blibli.com",
    "MY Pestle & Mortar": "pestle-mortar|pestlemortarclothing.com",
    "ZALORA - MY": "zalora|zalora.com.my",
    "Thai-voucher: You have a chance to win Starbucks 5,000 บาท, Enter now": "voucherthai|voucherthai.com",
    "Skinfe": "skinfe|skinfe.com",
    "HK Sailfish": "sailfish|sailfish.com.hk",
    "Hotels.com": "hotelscom|hotels.com",
    "Shogun2U (MY)": "shogun2u|shogun2u.com",
    "VN Linhkienso1.com": "linhkienso1|Linhkienso1.com",
    "Photobook (MY)": "photobook|photobook.com.my",
    "Wine Talk": "wine-talk|winetalk.com.my",
    "SG SOUFEEL": "soufeel|soufeel.com.sg",
    "MY Qoo10": "qoo10|qoo10.my",
    "TH HeadDaddy": "headdaddy|headdaddy.com",
    "VN 9am.vn": "9amvn|9am.vn",
    "VN NYX": "nyx|nyxvietnam.vn",
    "HK Suitcase.hk": "suitcase|suitcase.hk",
    "MY Khind": "khind|khind.com.my",
    "GlassesGroup AsiaPacific Sdn Bhd PH": "glassesonline|glassesonline.com.ph",
    "ID V3 Technology": "v3technology|v3technology.net",
    "ID Utees.me": "utees|Utees.me",
    "VN Sieuthicafe.vn": "sieuthicafe|sieuthicafe.vn",
    "Microsoft Southeast Asia": "microsoft|microsoftstore.com",
    "ZALORA - PH": "zalora|zalora.com.ph",
    "MY Wsken": "wsken|wsken.my",
    "ValueBasket.com Ltd": "valuebasket|valuebasket.com",
    "ID PNP Komputer": "pnp-komputer|gudangkomputer.net",
    "Bus Online Ticket": "busonlineticketcom|busonlineticket.com",
    "Nihonmart": "nihonmartbeauty|nihonmartbeauty.com",
    "Lafema": "lafema|orami.co.th",
    "MY i-Pmart": "i-pmart|ipmart.com.my",
    "Bay Ngay Giá Rẻ Cùng Bookin.vn": "bookin.vn|Bookin.vn",
    "Tudung2u": "tudung2u|Tudung2u.com.m",
    "MY Jayacom": "jayacom|jayacom.com.my",
    "Foxysales": "foxysales|foxysales.com",
    "TH Sephora": "sephora|sephora.th",
    "Ensogo Malaysia": "ensogo|ensogo.com",
    "MY Mighty Utan": "mightyutan|mightyutan.com.my",
    "VN SOUFEEL": "Soufeel|Soufeel.com.vn",
    "Rakuten": "rakuten|global.rakuten.com",
    "SG War Games Shop": "wargamesshop|wargamesshop.net",
    "Easibook.com Pte Ltd": "easybook|easibook.com",
    "PH Goods": "goods|goods.ph",
    "PH e-Mall": "e-mall|e-mall.com.ph",
    "VN khanhtoan.com": "khanhtoan|khanhtoan.com",
    "VN Penda (Electronics)": "penda|penda.vn",
    "PH Kaymu (Caps reached)": "Kaymu|Kaymu.ph",
    "SE-ED Online Shopping": "se-ed-online-shopping|se-ed.com",
    "JUNO - Giày nữ duyên dáng, Tự tin tỏa sáng !": "juno|juno.vn",
    "PT. GISTEX RETAILINDO (MINIMAL)": "gistexgroup|gistexgroup.com",
    "TH annth.com": "annth|annth.com",
    "(SC) HK, MY, SG, PH & ID Chicnova": "chicnova|chicnova.com",
    "PH eSHOPPING": "eshopping|eshopping.com.ph",
    "SG JML.sg": "jml|jml.sg",
    "ID Hijabenka.com": "hijabenka|hijabenka.com",
    "Trivago (MY-Desktop)": "trivago|trivago.com.my",
    "TH Tvdirect.tv": "tvdirect|tvdirect.tv",
    "PH ELN Online Store": "eln-online-store|elnstore.com",
    "PH JMB Albay Gadgets": "Albay Gadgets|jmbgadgets.com.ph",
    "VN Glosbejelwery.com": "glosbejewelry|Glosbejelwery.com",
    "MSIG: ประกันเดินทาง Travel Easy เพื่อนเดินทางตัวจริง": "msig|msig-thai.com",
    "MY Golden Rose": "goldenrose|goldenrose.com.my",
    "SG Techno Gadgets": "technogadgets|technogadgets.com.sg",
    "PH Little Emily Shop": "little-joe-woman|littleemilyshop.com",
    "Sendo.vn": "sendo|sendo.vn",
    "PH Filgifts": "filgifts|filgifts.com",
    "PH Kily": "kily|Kily.ph",
    "ID Razapo": "razapo|razapo.com",
    "ID Tamochi": "tamochi|Tamochi.com",
    "VN taingheviet.com": "taingheviet|taingheviet.com",
    "PH HIDEO WAKAMATSU": "hideo-wakamatsu|hideowakamatsu-ph.com",
    "Starbucks": "starbucks|starbucks.co.th",
    "HK MyDress": "mydress|mydress.com",
    "ZALORA - ID": "zalora|zalora.co.id",
    "ZEN Room CPA": "zen-rooms|zenrooms.com",
    "PH Perfume Philippines": "perfumes|perfumes.com.ph",
    "TH Thaicoolgadget": "thaicoolgadget|thaicoolgadget.com",
    "TH Goodspeedcomputer": "goodspeed-computer|goodspeed-computer.com",
    "TH Getzhop": "getzhop|getzhop.com",
    "PH PhilGrocer": "philgrocer|philgrocer.com",
    "(SC) ID & TH SOUFEEL": "soufeel|luxuriouscraving.com",
    "PH GreatValuePlus": "great-value-plus|greatValuePlus.ph",
    "Topvalueเว็บไซต์ขายสินค้าออนไลน์ ราคาถูกที่สุด": "topvalue|topvalue.com",
    "Test Company Shop HK": "Test|nan",
    "MY Store4online": "store4online|store4online.my",
    "ZUJI Travel Pte Ltd.": "zuji|zuji.com.sg",
    "(ALL) HK Jollychic.com": "jollychic|jollychic.com",
    "SG Kidz Style": "kidzstyle|kidzstyle.com",
    "ID Kucari.com": "kucari|kucari.com",
    "Cameralah (MY)": "cameralah|cameralah.com",
    "MY Demomo2u": "demomo2u|demomo2u.com",
    "Air Asia Go(MY)": "airasia|airasia.com",
    "ID Grobmart": "grobmart|Grobmart.com",
    "SG SGPCMart": "sgpcmart|sgpcmart.com",
    "SG Sgbest": "sgbest|sgbest.com",
    "PH urbantravellerco": "urbantravellerco|urbantravellerco.com",
    "MY Luxurious Craving": "luxuriouscraving|HO64",
    "PH Kaymu": "kaymu|Kaymu.ph",
    "Tohome": "tohome|tohome.com",
    "MY Ensogo": "ensogo|Ensogo.com.my",
    "PH QFlora": "qflora|qflora.com",
    "VN Noithatmiennam.com": "noithatmiennam|Noithatmiennam.com",
    "Fashion Valet": "fashionvalet|gemfive.com",
    "Groupon Singapore": "groupon|groupon.sg",
    "MY Sephora": "sephora|sephora.my",
    "โปรโมชั่นประกันภัยรถยนต์ชั้น 1 จาก Asia Direct Broker": "asia-direct|asiadirect.co.th",
    "VN chuthi.vn": "chuthi|chuthi.vn",
    "TH Sokenthai": "sokenthai|sokenthai.com",
    "FoodPanda HongKong": "foodpanda|foodpanda.hk",
    "SG Annielka": "annielka|annielka.com",
    "MY DASHER": "dasher|dasher.my",
    "VN Dalatlaptop.com": "dalatlaptop|dalatlaptop.com",
    "VN Thietbisoonline.com": "thietbisoonline|thietbisoonline.com",
    "HK Gadget.hk": "gadgethk|gadget.hk",
    "MYTOUR(Travel) - Đặt phòng ngay, 5000 khách sạn luôn có ưu đãi.  Giảm giá lên tới 50%.": "mytour|mytour.vn",
    "TH WearYouWant": "wearyouwant|wearyouwant.com",
    "Rakuten Indonesia": "rakuten|rakuten.co.id",
    "ID Muslimarket.com": "muslimarket|muslimarket.com",
    "Tarad": "tarad|tarad.com",
    "VN f5c": "f5c|f5c.vn",
    "PH Barato": "barato|barato.com.ph",
    "ID Lensza": "lensza|lensza.co.id",
    "LenYa Jewelry จิวเวลรี่ดีไซน์หรู ในราคาที่จับจ่ายได้": "lenya-jewelry|lenyajewelry.co.th",
    "VN iBasic": "ibasicvietnam|ibasicvietnam.com",
    "MY DIEM Duroil": "diemduroil|diemduroilstore.com",
    "GoDaddy.com": "godaddy|godaddy.com",
    "ShopAt7 by 7-Eleven": "shopat7|shopat7.com",
    "SG 21zoom": "21Zoom|21zoom.com",
    "Weloveshopping": "weloveshopping|portal.weloveshopping.com",
    "Reebonz": "reebonz|reebonz.com.my",
    "MY KLF Fashions": "klffashions|klffashions.com.my",
    "PH PhilCake": "philcake|philcake.com",
    "TH ezbuy": "ezbuy|ezbuy.co.th",
    "ROMWE": "romwe|romwe.com",
    "HERMISO": "hermiso|hermiso.com",
    "VN Caganu": "caganu|caganu.com",
    "Air Asia Go(TH)": "airasia|airasia.com",
    "MY Tudung2u": "tudung2u|tudung2u.com.my",
    "Lazada": "lazada|lazada.com.my",
    "Beauticool": "beauticool|beauticool.com",
    "HK SOUFEEL": "soufeel|luxuriouscraving.com",
    "TH Tsmorder": "tsmorder|tsmorder.com",
    "MY Harvey Norman": "harveynorman|harveynorman.com.my",
    "TH Intertoshop": "intertoshop|intertoshop.com",
    "TH i-smartlife": "i-smartlife|i-smartlife.com",
    "VN Thegioimaytinhbang.vn": "thegioimaytinhbang|thegioimaytinhbang.vn",
    "MY Atoz": "atoz|atoz2u.com",
    "MY Famcart": "famcart|famcart.com.my",
    "Nguyễn Kim – Thương hiệu số 1 về ngành bán lẻ điện tử tiêu dùng tại Việt Nam": "nguyen-kim|nguyenkim.com",
    "SG SG Watch Mall": "sgwatchmall|sgwatchmall.com",
    "PH Trendsndeals": "trends-n-deals|trendsndeals.com",
    "(SC) SG, PH, HK, ID WhatHeWants": "whathewants|whathewants.com.sg",
    "TH Hothitphone": "hothitphone|hothitphone.com",
    "VN Edena": "edena|edena.vn",
    "ID CSI": "csi|csi.co.id",
    "VN eshop24h.vn": "eshop24h|eshop24h.vn",
    "ช้อปวันนี้ที่ Cmart": "cmart|cmart.co.th",
    "MY Houz Depot": "houzdepot|emall.houzdepot.com",
    "TH Thaielectronicworld.info": "thaielectricworld|thaielectricworld.info",
    "VN Bigshop": "bigshop|bigshop.vn",
    "MY OPPO": "oppo|oppostore.com.my",
    "VN Babiday": "babiday|babiday.com",
    "Shopbop": "shopbop|shopbop.com",
    "PH Watchportal.com.ph": "watchportal|watchportal.com.ph",
    "MY Streetdeal": "streetdeal|streetdeal.my",
    "NESCAFÉ Red Cup : Commission สูงถึง 11.55% เครื่องชงกาแฟเนสกาแฟ เรดคัพ": "nescafe|nestle.co.th",
    "Tees.co.id": "tees|Tees.co.id",
    "Konvy.com โค้งสุดท้าย!! โปรโมชั่นใหญ่ ฉลองครบรอบ 4 ปี โปรฯแรงเครื่องสำอางร่วมลดราคากว่า 100 แบรนด์": "konvy|konvy.com",
    "Booking.com Hong Kong": "bookingcom|booking.com",
    "TH creationthai": "creationthai|creationthai.com",
    "Zen Zen Dream": "zenzen-dream|zenzendream.com",
    "Wedding": "weddingcommy|SS170",
    "PH SportsMNL": "sportsmnl|Sportsmnl.com|",
    "HK D C One": "dcone|dcone.hk",
    "TH invadeit.co.th": "invade-it|invadeit.co.th",
    "TH Dgjshop": "dgjshop|dgjshop.com",
    "PH PinasFlower": "pinasflowers|pinasflowers.com",
    "VN Sieu Thi Bep Nhap Khau": "Test Company Canada|sieuthibepnhapkhau.com.vn",
    "MY myVoucher": "nan|nan",
    "VN pinduphongtot.com": "pinduphongtot|pinduphongtot.com",
    "VN thietbidientuankiet.com": "thietbidientuankiet|thietbidientuankiet.com",
    "ID Batik Fractal": "batik-fractal.com|batikfractal.com",
    "TeezBee (MY)": "teezbee|teezbee.com",
    "SG Hermo.sg": "hermo|Hermo.sg",
    "DirectlyHERS": "directlyhers|directlyhers.com",
    "MY Bello2": "bello2|bello2.com",
    "PetLoft.com": "petloft|petLoft.com",
    "PH ExpressFlower": "expressflower|expressflower.ph",
    "PH FlowerAdvisor": "floweradvisor|floweradvisor.com",
    "ID Maeindonesia": "maeindonesia|Maeindonesia.com",
    "HK YesAsia.com": "yesasia|yesasia.com",
    "Test campaign for partners -CPL-": "Test|nan",
    "Ensogo": "ensogo|Ensogo.com.my",
    "SG HJ Luxury": "hjwatch|hjwatch.com",
    "PH SOUFEEL": "soufeel|soufeel.com.my",
    "TH Expansys": "expansys|expansys.in.th",
    "TH Ran Notebook": "rannotebook|rannotebook.com",
    "Christy Ng": "christy-ng|christyng.com",
    "VN fam.vn": "fam|fam.vn",
    "Easydeal (MY)": "easydeal|easydeal.com.my",
    "Tokopedia": "tokopedia|tokopedia.com",
    "VN Kimmobile.com": "kimmobile|kimmobile.com",
    "VN longbinh.com.vn": "longbinh|longbinh.com.vn",
    "Kiwi.com (Skypicker)": "kiwi|Kiwi.com",
    "MY ezbuy": "ezbuy|ezbuy.my",
    "MY Shoppu": "shoppu|shoppu.com.my",
    "Shoppu (MY)": "shoppu|shoppu.com.my",
    "Flower Advisor Malaysia": "floweradvisor|floweradvisor.com.my",
    "Flower Advisor Indonesia": "floweradvisor|floweradvisor.co.id",
    "VN Hoangsoncomputer.com": "hoangsoncomputer|hoangsoncomputer.com",
    "Cdiscount": "cdiscount|cdiscount.co.th",
    "VN Bigmua": "bigmua|bigmua.com",
    "ID Demoda": "demoda-asia|demoda.asia",
    "PH PinasGift": "pinasgift|pinasgifts.com",
    "ID Delima Cellular": "Ddelima-cellular|delimacellular.com",
    "ID Tokopedia": "tokopedia|tokopedia.com",
    "VN songlongmedia.com": "songlongmedia|songlongmedia.com",
    "VN Dmart.vn": "dmart|dmart.vn",
    "PH Weemall": "weemall|Weemall.com",
    "Su Estilo": "su-estilo|su-estilo.com",
    "MY BestBuyWorld.com": "bestbuy-world|bestbuy-world.com",
    "MY IKW": "ikwholesale|ikw.com.my",
    "PH Argomall": "argomall|argomall.com",
    "Expedia Singapore": "expedia|expedia.com.sg",
    "PH Abubot": "abubot|abubot.ph",
    "HK Baby-Kingdom eShop": "eshop.baby-kingdom|eshop.baby-kingdom.com",
    "ZUJI HK": "zuji|zuji.com.sg",
    "Thai-voucher: You have a chance to win Starbucks 10,000 บาท, Enter now": "voucherthai|voucherthai.com",
    "Babydash": "babydash|babydash.com.my",
    "Streetdeal Singapore": "streetdeal|streetdeal.my",
    "DELETED - Ensogo (MY)": "ensogo|Ensogo.com.my",
    "MY averagedrone": "averagedrone|averagedrone.my",
    "MY ebiz2u": "ebiz2u|ebiz2u.com.my",
    "StrawberryNET.com - Skincare-Makeup-Cosmetics-Fragrance": "strawberry|my.strawberrynet.com",
    "MY Mamakiddies": "mamakiddies|mamakiddies.com.my",
    "MK1 Offer": "Test|nan",
    "Air Asia Go(ID)": "airasiago|airasia.com",
    "MiniInTheBox.com": "miniinthebox|miniinthebox.com",
    "MY SmartMaster": "smartmaster|smartmaster.com.my",
    "OYO Rooms MY": "oyo|oyorooms.com",
    "Happy Fresh": "happyfresh|happyfresh.com",
    "Nike Hong Kong": "nike|nike.com",
    "NusaTrip (ID)": "nusatrip|nusatrip.com",
    "GrabTaxi -PH": "grab|grab.com",
    "Đặt phòng cùng VNTRIP - Xác nhận ngay, giảm tới 80%": "vntrip|vntrip.vn",
    "108tohome: Commission สูงถึง 11.55% เว็บไซต์ e-commerce ขายอาหารเสริมเพื่อสุขภาพของทุกคนในครอบครัว ภายใต้เครือบริษัทอาหารเสริมแบรนด์ชื่อดังอย่าง Vistra, Provamed, Bewel": "108tohomecom|108tohome.com",
    "Deca.vn _ Mang đến cho Mẹ và Bé những trải nghiệm mua sắm tuyệt vời nhất!!": "deca|deca.vn",
    "Tizen": "tizen|tizen.org",
    "JD.id": "jd|jd.id",
    "Doublewoot": "double-woot|double-woot.com",
    "Kinokuniya (TH)": "kinokuniya|thailand.kinokuniya.com",
    "TALAHA _ Giày nữ thời thượng cùng Hari Won": "talaha|talaha.vn",
    "KYNA- Học online cùng chuyên gia!": "kyna|kyna.vn",
    "Zilingo TH": "zilingo|zilingo.com",
    "SG shop.mymaha.com": "mymaha|shop.mymaha.com",
    "MY Game Hypermart": "gamehypermart|gamehypermart.com",
    "Bilna": "orami.co.id|orami.co.id",
    "Reebonz (ID)": "reebonz.com|reebonz.com",
    "Uniqlo (MY)": "uniqlo.com|uniqlo.com",
    "Dominos (ID)": "dominos.co.id|dominos.co.id",
    "Hermo Indonesia": "hermo.co.id|hermo.co.id",
    "Airpaz": "airpaz.com|airpaz.com",
    "Muslimarket": "muslimarket.com|muslimarket.com",
    "Reebonz (SG)": "reebonz.com|reebonz.com",
    "Alfacart": "alfacart.com|alfacart.com",
    "Fabelio (ID)": "fabelio.com|fabelio.com",
    "ID Papuros": "papuros-shop.com|papuros-shop.com",
    "Zilingo SG": "zilingo.com|zilingo.com",
    "MY EDZ": "edz.com.my|edz.com.my",
    "MY VivaQueenBee": "vivaqueenbee.com|vivaqueenbee.com",
    "Kay Collection": "kaycollection.com|kaycollection.com",
    "HK Dreamkart": "dreamkart.com.au|dreamkart.com.au",
    "SG Dreamkart": "dreamkart.com.au|dreamkart.com.au",
    "MY Major Drop": "majordrop.com|majordrop.com",
    "ID Sociolla": "sociolla.com|sociolla.com",
    "(SC) SG,MY,PH,ID,HK BigBigPlace": "bigbigplace.com|bigbigplace.com",
    "SG noxexpress.com": "noxexpress.com|noxexpress.com",
    "MY livlola.com": "livlola.com|livlola.com",
    "Citibank Credit Cards and Personal loan": "citi.com|citi.com",
    "Club Med": "clubmed.com.my|clubmed.com.my",
    "Hermo Malaysia": "hermo|hermo.my",
    "Lazada (ID)": "lazada|lazada.co.id",
    "Mumu (ID)": "mumu|mumu.id",
    "Trải nghiệm tuyệt vời khi đặt vé tại Bookin.vn": "bookin|bookin.vn",
    "Vinabook - Nhà sách trên mạng hàng đầu tại Việt Nam": "vinabook|vinabook",
    "Zilingo MY": "zilingo|zilingo.com",
    "Zilingo HK": "zilingo|zilingo.com",
    "VN Chiaki.vn": "chiaki|chiaki.vn",
    "VN khuyenmaicantho.com": "khuyenmaicantho|khuyenmaicantho.com",
    "SG tech2cool (CPS)": "tech2cool|tech2cool.com",
    "VN Kingshop.vn": "kingshop|kingshop.vn",
    "MY blip.my": "blip|blip.my",
    "PH marketplace.ph": "marketplace|marketplace.ph",
    "ID Kukuruyuk": "kosakata|kosakata.id",
    "SG Silkrouter": "silkrouter|silkrouter.com",
    "HK babypark.com.hk": "babypark|babypark.com.hk",
    "MY eloyza.com": "eloyza|eloyza.com",
    "MY globalit.com.my": "globalit|globalit.com.my",
    "ID Elevenia.co.id": "Elevenia|elevenia.co.id",
    "VN Ula.vn": "ula|ula.vn",
    "VN Eropi.com": "eropi|eropi.com",
    "MY ithyperstore.com": "ithyperstore|ithyperstore.com",
    "ID Es.id": "es|es.id",
    "MY beautify.my": "beautify|beautify.my",
    "(SC) EN stylekorean.com": "stylekorean|stylekorean.com",
    "TH The Outlet24": "theoutlet24|theoutlet24.com",
    "ID Alfacart": "alfacart|alfacart.com",
    "MY 28mall.com": "28mall|28mall.com",
    "MY adata.com": "adata|adata.com",
    "MY gemfive.com.my": "gemfive|gemfive.com.my",
    "MY unipro.my": "unipro|unipro.my",
    "BloomThis": "bloomthis|bloomthis.co",
    "Trivago (ID)": "trivago|trivago.co.id",
    "TheLorry (MY)": "thelorry|thelorry.com",
    "Wine Talk (Peninsular Malaysia)": "winetalk|winetalk.com.my",
    "Trivago (SG)": "trivago|trivago.co.sg",
    "Zataru": "zataru|zataru.com",
    "Tokopedia - Recharge": "tokopedia|tokopedia.com",
    "CatchThatBus": "catchthatbus|catchthatbus.com",
    "Koyara (MY)": "koyara|koyara.com",
    "Uber Driver Signup (Vietnam)": "uber|uber.com",
    "Uber Driver Signup (PH)": "uber|uber.com",
    "Uber Driver Signup (Malaysia)": "uber|uber.com",
    "Happy Bunch (MY)": "happybunch|happybunch.com.my",
    "Trivago (TH)": "trivago|trivago.co.th",
    "Tokopedia - Ticket": "tokopedia|tokopedia.com",
    "Photobook (PH)": "photobookphilippines|photobookphilippines.com",
    "Photobook (ID)": "photobookindonesia|photobookindonesia.com",
    "Big C Shopping Online บิ๊กซีช้อปปิ้งออนไลน์ ปรับโฉมใหม่ ท้าให้ช้อป": "bigc|bigc.co.th",
    "Honestbee": "honestbee|honestbee.my",
    "VN Lazada VN (Testing)": "lazada|lazada.vn",
    "HK Zalora (Testing)": "zalora|zalora.com.hk",
    "MY Zalora (Testing)": "zalora|zalora.com.my",
    "PH Zalora (Testing)": "zalora|zalora.com.ph",
    "SG Zalora (Testing)": "zalora|zalora.com.sg",
    "ID Zalora (Testing)": "zalora|zalora.com.id",
    "ID FlowerAdvisor": "floweradvisor|floweradvisor.co.id",
    "Onlyurs": "onlyurs|onlyurs.com",
    "ID Honestbee": "honestbee|id.honestbee.com",
    "VN Yousport.vn": "yousport|yousport.vn",
    "MY allaboutface.com.my": "allaboutface|allaboutface.com.my",
    "US jeulia.com": "jeulia|jeulia.com",
    "MY effortless.com.my": "effortless|effortless.com.my",
    "EntirelyPets (Testing)": "entirelypets.com|entirelypets.com",
    "Strawberry (Testing)": "strawberrynet|my.strawberrynet.com",
    "MY bookurve.com": "bookurve|bookurve.com",
    "Ssense (Testing)": "ssense|ssense.com",
    "Gamersgate (Testing)": "gamersgate|gamersgate.com",
    "Miniinthebox (Testing)": "miniinthebox|miniinthebox.com",
    "Tmart (Testing)": "tmart|tmart.com",
    "Beautifiedyou (Testing)": "beautifiedyou|beautifiedyou.com",
    "SheIn (Testing)": "shein|shein.com",
    "MY ashbenimble.com": "ashbenimble|ashbenimble.com",
    "MY Kidsroom (Testing)": "kidsroom|kids-room.com",
    "MY Beddinginn (Testing)": "beddinginn|beddinginn.com",
    "Banggood (Testing)": "banggood|banggood.com",
    "SG Heatwaveshoes.com": "heatwaveshoes|heatwaveshoes.com",
    "VN Bookbuy.vn": "bookbuy|bookbuy.vn",
    "HK ztore.com": "ztore|ztore.com",
    "MY antstribe.com": "antstribe|antstribe.com",
    "HK vopmart.com": "vopmart|vopmart.com",
    "SG naiise.com": "naiise|naiise.com",
    "PH widgetcity.com.ph": "widgetcity|widgetcity.com.ph",
    "SG megafash.com": "megafash|megafash.com",
    "VN Sporter.vn": "sporter|sporter.vn",
    "HK suchprice.hk": "suchprice|suchprice.hk",
    "ID Hellobeauty.id": "hellobeauty|hellobeauty.id",
    "MY mylovelybaby.com.my": "mylovelybaby|mylovelybaby.com.my",
    "VN Winwinshop88.com": "winwinshop88|winwinshop88.com",
    "VN Dyoss.com": "dyoss|dyoss.com",
    "MY boozeat.com": "boozeat|boozeat.com",
    "MY gloo.com.my": "gloo|gloo.com.my",
    "MY shopee.com.my": "shopee|shopee.com.my",
    "SG shopee.sg": "shopee|shopee.sg",
    "TH J.I.B.": "jib|jib.co.th",
    "MY dicksonchew.my": "dicksonchew|dicksonchew.my",
    "MY senheng.com.my": "senheng|senheng.com.my",
    "MY harveynorman.com.my": "harveynorman|harveynorman.com.my",
    "SG tokichoi.com": "tokichoi|tokichoi.com",
    "SG harveynorman.com.sg": "harveynorman|harveynorman.com.sg",
    "PH crazydomains.ph": "crazydomains|crazydomains.ph",
    "MY Weshop.my": "weshop|weshop.my",
    "VN Thoitrangtichtac.com": "thoitrangtichtac|thoitrangtichtac.com",
    "ID Gogobli": "gogobli|gogobli.com",
    "TH Orami (Testing)": "orami|orami.co.th",
    "VN Donghohieu.vn": "donghohieu|donghohieu.vn",
    "SG Lazada SG (Testing)": "lazada|lazada.sg",
    "TH Lazada TH (Testing)": "lazada|lazada.co.th",
    "PH Lazada PH (Testing)": "lazada|lazada.com.ph",
    "MY Lazada MY (Testing)": "lazada|lazada.com.my",
    "ID Lazada ID (Testing)": "lazada|lazada.co.id",
    "MY FOS (Testing)": "fos|fos.com.my",
    "ID Matahari Mall (Testing)": "mataharimall|mataharimall.com",
    "ID Seekmi": "seekmi|seekmi.com",
    "TH Central (Testing)": "central|central.co.th",
    "TH Konvy (Testing)": "konvy|konvy.com",
    "TH ShopAt24 (Testing)": "shopat24|shopat24.com",
    "VN Yes24 (Testing)": "yes24|yes24.com",
}
